name: theanxiousgrape
favicon: null
layout_spectrum: 0.9412040957249701
typography_spectrum: 0.41384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.35274672973901033
  lightness: 0.6913558021187782
  saturation: 0.049456755397841334
  rhythmicContrast: 0.8608758649788797
purpose: []
